// Use USER namespace so classes are always writable in Community Edition
set ns="USER"

zn ns
write !,"[testops] loading classes...",!
do $system.OBJ.LoadDir("/opt/testops/src/cls","ck",,1)

write !,"[testops] applying schema...",!
do ##class(TestOps.Util.DB).ApplySchema("/opt/testops/src/sql/schema.sql")

write !,"[testops] seeding admin...",!
do ##class(TestOps.Util.DB).EnsureAdmin()

zn "%SYS"
write !,"[testops] configuring webapp...",!

// Recreate CSP application
do ##class(Security.Applications).Delete("/csp/testops")
do ##class(Security.Applications).Create("/csp/testops")

kill props
set props("Enabled")=1
set props("NameSpace")=ns
set props("DispatchClass")="TestOps.Api.Dispatch"
set props("Recurse")=1
set props("AllowedIPAddresses")="*"

// IMPORTANT: CSP-level auth OFF (API does its own Bearer token)
set props("AutheEnabled")=64     // 64 = unauthenticated

// keep it максимально простым
set props("UseCookies")=0
set props("Resource")="%All"

do ##class(Security.Applications).Modify("/csp/testops", .props)

write !,"[testops] done",!
halt